project_id = "eozhtxplgwzwytulxlhz"

[functions.kiwify-webhook]
verify_jwt = false

[functions.suggest-names]
verify_jwt = false

[functions.elevenlabs-music-generator]
verify_jwt = false

[functions.templated-render]
verify_jwt = false
